### ISSUE TITLE
sprint response 필드명 변경 요청

### ISSUE THREAD

**Issue by mottoslo** [HangHae-Sprint/sprint-client#8]
sprint 관련 정보를 주는 response에서 필드(모집 포지션) 정보를 담고있는 필드의 이름이 현재 fields인데, 컬렉션을 복수형으로 명시하지 않고 컬렉션의 타입을 붙여주기로 한 코드컨벤션과 맞지 않아 fieldInfoList로 변경하고자 합니다. 해당 이름으로 받으려면 API 명세를 수정해야해서 혹시 필드명 수정이 가능하실지 Issue 남깁니다. 댓글 달아주시면 API 명세에 반영하겠습니다

<변경사항>
 sprint작성기능 request
**기존 :** 
{
   title : “String”   
   content : “String”
   sprintType : “Project”
   fields : [
               {
      ”fieldName” : “backend”
      “fieldMaxNum” : 3
                },
               {
      ”fieldName” : “frontend”
      “fieldMaxNum” : 2
                }
                …….
              ]
}

**변경**

{
   title : “String”   
   content : “String”
   sprintType : “Project”
   **fieldInfoList** : [
               {
      ”fieldName” : “backend”
      “fieldMaxNum” : 3
                },
               {
      ”fieldName” : “frontend”
      “fieldMaxNum” : 2
                }
                …….
              ]
}

**Comment by stella0905** [comment]
네 변경 가능합니다~! 명세서 같이 변경해주시면 변경된걸로 반영 하겠습니다.
